name: Asm CI

on:
  pull_request

jobs:
  tests:
    name: Testing asm
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install binutils g++ cmake nasm python3 dos2unix
        sudo apt install haskell-stack netbase
        stack upgrade
        stack install random optparse-applicative

    - name: Check line spaces
      run: |
        pushd $GITHUB_WORKSPACE
        ci-extra/check-lines.sh
        popd

    - name: Check formatting
      run: |
        ci-extra/check-asm-formatting.py

    - name: Compile tests
      run: stack ghc -- -o test test.hs

    - name: Build
      run: ./build.sh

    - name: Test sub
      run: ./test sub --bin ./build/sub --max-qwords 128 --tests 1000

    - name: Test mul
      run: ./test mul --bin ./build/mul --max-qwords 128 --tests 1000
