name: Asm CI

on:
  push:
    paths:
      - 'asm/**'
  pull_request:
    paths:
      - 'asm/**'

jobs:
  tests:
    name: Testing asm
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install binutils g++ cmake nasm python3 dos2unix
          sudo apt install haskell-stack netbase
          stack upgrade
          stack install random optparse-applicative

      - name: Check line spaces
        run: |
          asm/ci-extra/check-lines.sh

      - name: Check formatting
        run: |
          asm/ci-extra/check-asm-formatting.py

      - name: Compile tests
        run: cd asm && stack ghc -- -o test test.hs

      - name: Build
        run: cd asm && ./build.sh

      - name: Test sub
        run: cd asm && ./test sub --bin ./build/sub --max-qwords 128 --tests 1000

      - name: Test mul
        run: cd asm && ./test mul --bin ./build/mul --max-qwords 128 --tests 1000
