name: Bimap CI

on:
  push:
    paths:
      - 'bimap/**'
  pull_request:
    paths:
      - 'bimap/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/base-ci.yml
    with:
      folder: bimap
      name: Bimap
