name: Bimap CI

on:
  push:
    paths:
      - 'bimap/**'
  pull_request:
    paths:
      - 'bimap/**'

jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Check line breaks
        run: ./bimap/ci-extra/check-lines.sh

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          check-path: 'bimap'

  test:
    needs: formatting-check
    name: "Test (${{ matrix.compiler.cc }}, ${{ matrix.build_type }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
        build_type: [Debug, Release, RelWithDebInfo, Sanitized]
        exclude:
          - build_type: Sanitized

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install base dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build g++ clang valgrind dos2unix git curl zip unzip

      - name: Setup vcpkg and install Catch2
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install catch2

      - name: Configure & build
        run: |
          mkdir -p bimap/build
          cd bimap/build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . -- -j$(nproc)

      - name: Run tests
        run: |
          cd bimap/build
          ./tests

      - name: Run tests with valgrind
        if: ${{ matrix.build_type == 'RelWithDebInfo' }}
        run: |
          cd bimap/build
          valgrind --leak-check=full ./tests
