name: Bitset CI

on:
  push:
    paths:
      - 'bitset/**'
  pull_request:
    paths:
      - 'bitset/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/base-ci.yml
    with:
      folder: bitset
      name: Bitset
