name: Intrusive-List CI

on:
  push:
    paths:
      - 'intrusive-list/**'
  pull_request:
    paths:
      - 'intrusive-list/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/base-ci.yml
    with:
      folder: intrusive-list
      name: Intrusive-List
